### ISSUE TITLE
Really laggy on mobile

### ISSUE THREAD

**Issue by ghost** [davidgilbertson/easy-ease#3]
The animation on PC is fine, but when I open it on my mobile it is slow and takes twice as long as on PC. Is there any way to synchronize it on all devices?

**Comment by davidgilbertson** [comment]
This is most likely because the code that you're passing to `onStep` is taking more than 16ms to complete on mobile. You can throttle the CPU in Chrome on desktop and use the DevTools performance tab to see what's taking so long.

If you're manipulating the DOM in any way that causes a repaint, this might be your problem. For most things DOM related you can use CSS animations instead.

I'll close this as I don't believe it's an issue with the library, but if you're stuck feel free to share your code and I'll see if I can help.

**Comment by ghost** [comment]
Would it be possible to lower framerate to make up for the throttling?

**Comment by davidgilbertson** [comment]
Hmm, if I understand correctly, you're suggesting that the library would calculate how long it's taking to execute the code in `onStep` and adjust the number of steps for the remainder of the animation? I like the idea, but this would need to be done for every single step, potentially slowing down the whole thing for all users.

**Comment by ghost** [comment]
No, I mean to change it to 30 fps for everyone.

**Comment by davidgilbertson** [comment]
Oh, no I'd like to leave it at 60 FPS. 

You could fork (or even just copy/paste, it's very small) and make the change. But currently it uses `requestAnimationFrame`, not a hardcoded 60 FPS, so you'd need to change that logic.

I wrote a post about the inner workings if you're interested https://medium.com/hackernoon/writing-an-easing-function-a-slightly-interesting-story-70ce667c212a
